theme: jekyll-theme-dinky
include: [team6/docs/2-Using ClassScheduler to Make a Personal Schedule/1-Selecting School.md,  team6/docs/2-Using ClassScheduler to Make a Personal Schedule/2-Selecting Session.md]
